# This is a GitHub workflow defining a set of jobs with a set of steps.
# ref: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions
#
name: Tests

on:
  pull_request:
    paths-ignore:
      - "**.md"
      - ".github/workflows/*.yaml"
      - "!.github/workflows/test.yaml"
  push:
    paths-ignore:
      - "**.md"
      - ".github/workflows/*.yaml"
      - "!.github/workflows/test.yaml"
    branches-ignore:
      - "dependabot/**"
      - "pre-commit-ci-update-config"
    tags: ["**"]
  workflow_dispatch:

env:
  LDAP_HOST: 127.0.0.1

jobs:
  test:
    runs-on: ubuntu-22.04
    timeout-minutes: 10

    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python-version }}"

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[test]"

      - name: List packages
        run: pip freeze

      - name: Run tests
        run: |
          # start LDAP server
          ci/docker-ldap.sh

          pytest --cov=ldapauthenticator

      # GitHub action reference: https://github.com/codecov/codecov-action
      - uses: codecov/codecov-action@v4
